### ISSUE TITLE
Feature request: ability to use different directories for each creator

### ISSUE THREAD

**Issue by elnareen** [Foxite/PatreonDownloader#4]
Thanks a lot for your program!

I just discovered it and he is currently saving my life archiving about 60 pages from an creator, after I tried doing it by hand...

However, since it is harcoded to use the PatreonDownloader directory for everything, in practice it means it is not possible to use it to download multiple campaigns without renaming/swapping this folder between each one.

Would it be possible in a future version to add the possibility to either work in different PatreonDownloader subfolders depending on the creator, or add a way to specify a custom working directory?

**Comment by Foxite** [comment]
Hi, I have released a new version that lets you specify the location for the PatreonDownloader folder, as well as the name of a subfolder that will be created inside that folder. Please tell me if it works.

**Comment by elnareen** [comment]
Thanks!

However, there is no *.exe file in the ZIP release, only a PatreonDownloader file without extension which is not recognized as a Windows application, even when adding an extension manually. Is it expected?

**Comment by Foxite** [comment]
Ah. Apparently it only includes exe files if you build it on windows. I've updated the release package so that it now contains a `start.cmd` that will run the program, provided that you have .NET installed (which I'm pretty sure you already did, otherwise I think you wouldn't be able to start the program before - but do tell me if it doesn't work).

If you're curious btw, that file you mentioned is a Linux executable. The real program is inside PatreonDownloader.dll which must be executed using .NET. If you make a build of this project it gives you an executable which does just that, for whichever platform you're currently using.

The "real" method of releasing a .NET program is to use something called "dotnet publish", which produces not only a build of your program but also includes the entire .NET runtime which increases the size of the package to probably around 50 to 80 megabytes. Most windows computers these days already have .NET installed, so it's not necessary to include all of it.

**Comment by elnareen** [comment]
Thanks: I thought so when you mentioned in the other issue you now use Arch Linux :)

Using start.cmd works without problem, and the new subfolder feature as well: I moved all the content in PatreonDownloader to a new subfolder and resumed the campaign from here without issue ^^
